// Mocks generated by Mockito 5.4.6 from annotations
// in radarscholar/test/views/discovery_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:radarscholar/models/scholarship.dart' as _i2;
import 'package:radarscholar/repositories/scholarship_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeScholarshipListResponse_0 extends _i1.SmartFake
    implements _i2.ScholarshipListResponse {
  _FakeScholarshipListResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScholarship_1 extends _i1.SmartFake implements _i2.Scholarship {
  _FakeScholarship_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ScholarshipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScholarshipRepository extends _i1.Mock
    implements _i3.ScholarshipRepository {
  MockScholarshipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ScholarshipListResponse> getScholarships({
    int? page = 1,
    int? pageSize = 20,
    String? search,
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getScholarships, [], {
              #page: page,
              #pageSize: pageSize,
              #search: search,
              #status: status,
            }),
            returnValue: _i4.Future<_i2.ScholarshipListResponse>.value(
              _FakeScholarshipListResponse_0(
                this,
                Invocation.method(#getScholarships, [], {
                  #page: page,
                  #pageSize: pageSize,
                  #search: search,
                  #status: status,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ScholarshipListResponse>);

  @override
  _i4.Future<_i2.Scholarship> getScholarshipDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getScholarshipDetail, [id]),
            returnValue: _i4.Future<_i2.Scholarship>.value(
              _FakeScholarship_1(
                this,
                Invocation.method(#getScholarshipDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Scholarship>);
}
