"""add last_verified_live_at to scholarships

Revision ID: 7fdda7f7aa30
Revises: d634cf614e8c
Create Date: 2026-09-26 16:33:28.226707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdda7f7aa30'
down_revision: Union[str, Sequence[str], None] = 'd634cf614e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarships', sa.Column('last_verified_live_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarships', 'last_verified_live_at')
    # ### end Alembic commands ###