"""create_scholarships_tables

Revision ID: ce5efc284f0e
Revises: b1c935995d61
Create Date: 2026-09-21 23:19:20.373827

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce5efc284f0e'
down_revision: str | Sequence[str] | None = 'b1c935995d61'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('crawl_allowed', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_sources_provider_name'), 'scholarship_sources', ['provider_name'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('application_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['scholarship_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_title'), 'scholarships', ['title'], unique=False)
    op.create_table('scholarship_benefits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scholarship_id', sa.Uuid(), nullable=False),
    sa.Column('benefit_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scholarship_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scholarship_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_type', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_table('scholarship_requirements')
    op.drop_table('scholarship_benefits')
    op.drop_index(op.f('ix_scholarships_title'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_scholarship_sources_provider_name'), table_name='scholarship_sources')
    op.drop_table('scholarship_sources')
    # ### end Alembic commands ###
