"""create_m10_admin_and_crawler_tables

Revision ID: d634cf614e8c
Revises: 1ad04e74ca2a
Create Date: 2026-09-25 00:34:19.926915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd634cf614e8c'
down_revision: Union[str, Sequence[str], None] = '1ad04e74ca2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sources_attempted', sa.Integer(), nullable=False),
    sa.Column('sources_succeeded', sa.Integer(), nullable=False),
    sa.Column('sources_failed', sa.Integer(), nullable=False),
    sa.Column('scholarships_created', sa.Integer(), nullable=False),
    sa.Column('scholarships_updated', sa.Integer(), nullable=False),
    sa.Column('scholarships_skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_profiles', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # We set default=False earlier but existing rows will be NULL, so we update them and make it False.
    op.execute("UPDATE user_profiles SET is_admin = 0 WHERE is_admin IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'is_admin')
    op.drop_table('crawl_runs')
    # ### end Alembic commands ###
